compatibility_date = "2023-10-16"
main = "src/index.ts"
name = "webdav-org"

node_compat = true

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/r2/api/workers/workers-api-usage/
[[r2_buckets]]
binding = "bucket" # <~ valid JavaScript variable name
bucket_name = "webdav-org-bucket"

# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
head_sampling_rate = 1
